# -*- coding: utf-8 -*-
"""Language Translation using  IBM Watson.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12Z8kFpfbRZZe169vkXWp21SayZ7HhqpM
"""

!pip install ibm_watson

API_key = 'I6eCsG3fVH6k-L_4MYAbvgD_eoXk1U480UC8GezkUUcc'
url = 'https://api.eu-gb.language-translator.watson.cloud.ibm.com/instances/209d939b-59cb-4001-a707-013244cee735'

from ibm_watson import LanguageTranslatorV3

from ibm_cloud_sdk_core.authenticators import IAMAuthenticator

authenticator = IAMAuthenticator(apikey=API_key)
langtranslator = LanguageTranslatorV3(version='2018-05-01',
                                     authenticator=authenticator)
langtranslator.set_service_url(url)

"""<table>
            <caption>Table 1. Translatable languages</caption>
            <thead>
              <tr class="doc-tr-even">
                <th>Language</th>
                <th style="text-align:center">Language code</th>
                <th>Language</th>
                <th style="text-align:center">Language code</th>
              </tr>
            </thead>
            <tbody>
              <tr class="doc-tr-odd">
                <td><a href="#arabic">Arabic</a></td>
                <td style="text-align:center"><code>ar</code></td>
                <td><a href="#korean">Korean</a></td>
                <td style="text-align:center"><code>ko</code></td>
              </tr>
              <tr class="doc-tr-even">
                <td><a href="#basque">Basque</a> <strong>[1]</strong></td>
                <td style="text-align:center"><code>eu</code></td>
                <td><a href="#latvian">Latvian</a></td>
                <td style="text-align:center"><code>lv</code></td>
              </tr>
              <tr class="doc-tr-odd">
                <td><a href="#bengali">Bengali</a></td>
                <td style="text-align:center"><code>bn</code></td>
                <td><a href="#lithuanian">Lithuanian</a></td>
                <td style="text-align:center"><code>lt</code></td>
              </tr>
              <tr class="doc-tr-even">
                <td><a href="#bosnian">Bosnian</a></td>
                <td style="text-align:center"><code>bs</code></td>
                <td><a href="#malay">Malay</a></td>
                <td style="text-align:center"><code>ms</code></td>
              </tr>
              <tr class="doc-tr-odd">
                <td><a href="#bulgarian">Bulgarian</a></td>
                <td style="text-align:center"><code>bg</code></td>
                <td><a href="#malayalam">Malayalam</a></td>
                <td style="text-align:center"><code>ml</code></td>
              </tr>
              <tr class="doc-tr-even">
                <td><a href="#catalan">Catalan</a> <strong>[1]</strong></td>
                <td style="text-align:center"><code>ca</code></td>
                <td><a href="#maltese">Maltese</a></td>
                <td style="text-align:center"><code>mt</code></td>
              </tr>
              <tr class="doc-tr-odd">
                <td><a href="#chinese-simplified">Chinese (Simplified)</a></td>
                <td style="text-align:center"><code>zh</code></td>
                <td><a href="#montenegrin">Montenegrin</a> <strong>[2]</strong></td>
                <td style="text-align:center"><code>cnr</code></td>
              </tr>
              <tr class="doc-tr-even">
                <td><a href="#chinese-traditional">Chinese (Traditional)</a></td>
                <td style="text-align:center"><code>zh-TW</code></td>
                <td><a href="#nepali">Nepali</a></td>
                <td style="text-align:center"><code>ne</code></td>
              </tr>
              <tr class="doc-tr-odd">
                <td><a href="#croatian">Croatian</a></td>
                <td style="text-align:center"><code>hr</code></td>
                <td><a href="#norwegian-bokmal">Norwegian Bokmål</a></td>
                <td style="text-align:center"><code>nb</code></td>
              </tr>
              <tr class="doc-tr-even">
                <td><a href="#czech">Czech</a></td>
                <td style="text-align:center"><code>cs</code></td>
                <td><a href="#polish">Polish</a></td>
                <td style="text-align:center"><code>pl</code></td>
              </tr>
              <tr class="doc-tr-odd">
                <td><a href="#danish">Danish</a></td>
                <td style="text-align:center"><code>da</code></td>
                <td><a href="#portuguese">Portuguese</a></td>
                <td style="text-align:center"><code>pt</code></td>
              </tr>
              <tr class="doc-tr-even">
                <td><a href="#dutch">Dutch</a></td>
                <td style="text-align:center"><code>nl</code></td>
                <td><a href="#romanian">Romanian</a></td>
                <td style="text-align:center"><code>ro</code></td>
              </tr>
              <tr class="doc-tr-odd">
                <td><a href="#english">English</a></td>
                <td style="text-align:center"><code>en</code></td>
                <td><a href="#russian">Russian</a></td>
                <td style="text-align:center"><code>ru</code></td>
              </tr>
              <tr class="doc-tr-even">
                <td><a href="#estonian">Estonian</a></td>
                <td style="text-align:center"><code>et</code></td>
                <td><a href="#serbian">Serbian</a> <strong>[3]</strong></td>
                <td style="text-align:center"><code>sr</code></td>
              </tr>
              <tr class="doc-tr-odd">
                <td><a href="#finnish">Finnish</a></td>
                <td style="text-align:center"><code>fi</code></td>
                <td><a href="#sinhala">Sinhala</a></td>
                <td style="text-align:center"><code>si</code></td>
              </tr>
              <tr class="doc-tr-even">
                <td><a href="#french">French</a></td>
                <td style="text-align:center"><code>fr</code></td>
                <td><a href="#slovak">Slovak</a></td>
                <td style="text-align:center"><code>sk</code></td>
              </tr>
              <tr class="doc-tr-odd">
                <td><a href="#french-canadian">French (Canadian)</a></td>
                <td style="text-align:center"><code>fr</code></td>
                <td><a href="#slovenian">Slovenian</a></td>
                <td style="text-align:center"><code>sl</code></td>
              </tr>
              <tr class="doc-tr-even">
                <td><a href="#german">German</a></td>
                <td style="text-align:center"><code>de</code></td>
                <td><a href="#spanish">Spanish</a></td>
                <td style="text-align:center"><code>es</code></td>
              </tr>
              <tr class="doc-tr-odd">
                <td><a href="#greek">Greek</a></td>
                <td style="text-align:center"><code>el</code></td>
                <td><a href="#swedish">Swedish</a></td>
                <td style="text-align:center"><code>sv</code></td>
              </tr>
              <tr class="doc-tr-even">
                <td><a href="#gujarati">Gujarati</a></td>
                <td style="text-align:center"><code>gu</code></td>
                <td><a href="#tamil">Tamil</a></td>
                <td style="text-align:center"><code>ta</code></td>
              </tr>
              <tr class="doc-tr-odd">
                <td><a href="#hebrew">Hebrew</a></td>
                <td style="text-align:center"><code>he</code></td>
                <td><a href="#telugu">Telugu</a></td>
                <td style="text-align:center"><code>te</code></td>
              </tr>
              <tr class="doc-tr-even">
                <td><a href="#hindi">Hindi</a></td>
                <td style="text-align:center"><code>hi</code></td>
                <td><a href="#thai">Thai</a></td>
                <td style="text-align:center"><code>th</code></td>
              </tr>
              <tr class="doc-tr-odd">
                <td><a href="#hungarian">Hungarian</a></td>
                <td style="text-align:center"><code>hu</code></td>
                <td><a href="#turkish">Turkish</a></td>
                <td style="text-align:center"><code>tr</code></td>
              </tr>
              <tr class="doc-tr-even">
                <td><a href="#irish">Irish</a></td>
                <td style="text-align:center"><code>ga</code></td>
                <td><a href="#ukrainian">Ukrainian</a></td>
                <td style="text-align:center"><code>uk</code></td>
              </tr>
              <tr class="doc-tr-odd">
                <td><a href="#indonesian">Indonesian</a></td>
                <td style="text-align:center"><code>id</code></td>
                <td><a href="#urdu">Urdu</a></td>
                <td style="text-align:center"><code>ur</code></td>
              </tr>
              <tr class="doc-tr-even">
                <td><a href="#italian">Italian</a></td>
                <td style="text-align:center"><code>it</code></td>
                <td><a href="#vietnamese">Vietnamese</a></td>
                <td style="text-align:center"><code>vi</code></td>
              </tr>
              <tr class="doc-tr-odd">
                <td><a href="#japanese">Japanese</a></td>
                <td style="text-align:center"><code>ja</code></td>
                <td><a href="#welsh">Welsh</a></td>
                <td style="text-align:center"><code>cy</code></td>
              </tr>
            </tbody>
          </table>
"""

translation = langtranslator.translate(text='Hello World',model_id='en-hi')

translation.get_result()

text = 'According to consensus in modern genetics anatomically modern humans first arrived on the Indian subcontinent from Africa between 73,000 and 55,000 years ago.[1] However, the earliest known human remains in South Asia date to 30,000 years ago. Settled life, which involves the transition from foraging to farming and pastoralism, began in South Asia around 7,000 BCE. At the site of Mehrgarh presence can be documented of the domestication of wheat and barley, rapidly followed by that of goats, sheep, and cattle.[2] By 4,500 BCE, settled life had spread more widely,[2] and began to gradually evolve into the Indus Valley Civilization, an early civilization of the Old world, which was contemporaneous with Ancient Egypt and Mesopotamia. This civilisation flourished between 2,500 BCE and 1900 BCE in what today is Pakistan and north-western India, and was noted for its urban planning, baked brick houses, elaborate drainage, and water supply.[3]'
translation = langtranslator.translate(text=text,model_id='en-hi')
translation.get_result()

translation.get_result()['translations'][0]['translation']

